site_name: Fides - Case Definition Language 
site_description: An extensible framework and naming protocol for defining and managing justice-related data structures and behaviours, designed to facilitate the safe use of artificial intelligence (AI) within UK Justice and Forensics System.
site_author: Jonathan Bowker
site_url: https://jonathanbowker.github.io/criminal-justice-schema
repo_url: https://github.com/JonathanBowker/criminal-justice-schema
repo_name: GitHub

theme:
  name: material
  palette:
    - scheme: default
      primary: deep purple
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  features:
    - content.code.copy
    - header.autohide
  icon:
    fontawesome: true
  language: en

plugins:
  - search
  - tags

extra:
  meta:
    - name: keywords
      content: justice, schema, definition language, data standard, legal technology, criminal justice
    - property: og:title
      content: Judicial Electronic Data Interchange Language
    - property: og:description
      content: A comprehensive schema for managing justice-related data.
    - property: og:url
      content: https://jonathanbowker.github.io/criminal-justice-schema
    - property: og:image
      content: https://example.com/social-image.png

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.tasklist
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tilde
  - pymdownx.magiclink
  - pymdownx.inlinehilite
  - pymdownx.extra
  - md_in_html

nav:
  - Introduction: index.md
  - References:
      - Data Standards: references/data_standards.md
      - Glossary: references/glossary.md
  - Dataset Catalogue:
      - Overview: data_catalogue/0.overview.md
      - Criminal Prosecution Reference: data_catalogue/1.criminal_prosecution_reference.md
      - Hearing: data_catalogue/2.hearing.md
      - Offence: data_catalogue/3.offence.md
      - Evidence: data_catalogue/12.evidence.md
      - Organisation Unit Identifier: data_catalogue/4.organisation_unit_identifier.md
      - Person: data_catalogue/5.person.md
      - Postal Address: data_catalogue/6.postal_address.md
      - Result (Fixed): data_catalogue/7.result_fixed.md
      - Result Qualifier (Fixed): data_catalogue/8.result_qualifier_fixed.md
      - Role: data_catalogue/9.role.md
      - System ID: data_catalogue/10.system_id.md
      - UK Internal Country: data_catalogue/11.uk_internal_country.md          
  - Case Data Map:
      - Overview: taxonomy/overview.md
  - Examples Files:
      - Yaml Examples: examples/yaml-examples.md
      - Json Examples: examples/json-examples.md
